# PlatformIO pre-build script: gzips src/web/page/index.html into a C array
# (src/web/page_gz.h) so that the page is part of the firmware: no LittleFS,
# no Internet, always the same version as the firmware (plan §10.2).
# The header is generated, not versioned; it is only rewritten when it changes.
import gzip
import os

Import("env")  # noqa: F821 (provided by PlatformIO)

BUDGET = 30 * 1024  # plan §10.2: < 30 kB gzip

project = env["PROJECT_DIR"]  # noqa: F821
source = os.path.join(project, "src", "web", "page", "index.html")
target = os.path.join(project, "src", "web", "page_gz.h")

with open(source, "rb") as f:
    html = f.read()
# mtime=0: identical input gives an identical header (no needless rebuild).
data = gzip.compress(html, compresslevel=9, mtime=0)

lines = [
    "// Generated by scripts/embed_page.py from src/web/page/index.html. Do not edit.",
    "#pragma once",
    "#include <Arduino.h>",
    "",
    "static const size_t PAGE_GZ_LEN = %d;" % len(data),
    "static const uint8_t PAGE_GZ[] PROGMEM = {",
]
for i in range(0, len(data), 16):
    lines.append("  " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
lines.append("};")
content = "\n".join(lines) + "\n"

old = None
if os.path.exists(target):
    with open(target, "r") as f:
        old = f.read()
if old != content:
    with open(target, "w", newline="\n") as f:
        f.write(content)

print("embed_page: index.html %d bytes -> %d bytes gzip%s" % (
    len(html), len(data), "" if len(data) <= BUDGET else " (OVER THE 30 kB BUDGET)"))
