# PlatformIO pre-build script (improvement D4): firmware version from git.
# Writes src/version_gen.h with FIRMWARE_VERSION = `git describe --tags --dirty
# --always` (e.g. "v0.1-3-g7a20d46-dirty", or just the short hash without tags).
# The header is generated, not versioned, and only rewritten when it changes,
# so that a build without any change does not recompile everything.
import os
import subprocess

Import("env")  # noqa: F821 (provided by PlatformIO)

project = env["PROJECT_DIR"]  # noqa: F821
target = os.path.join(project, "src", "version_gen.h")

try:
    version = subprocess.check_output(
        ["git", "describe", "--tags", "--dirty", "--always"],
        cwd=project, stderr=subprocess.DEVNULL, text=True).strip()
except (OSError, subprocess.CalledProcessError):
    version = "unknown"
version = version.replace("\\", "").replace('"', "")

content = (
    "// Generated by scripts/git_version.py. Do not edit.\n"
    "#pragma once\n"
    '#define FIRMWARE_VERSION "%s"\n' % version
)

old = None
if os.path.exists(target):
    with open(target, "r") as f:
        old = f.read()
if old != content:
    with open(target, "w", newline="\n") as f:
        f.write(content)

print("git_version: %s" % version)
