#include "DebugUi.h"

#include "board/Log.h"
#include "control/Actions.h"
#include "states/StateMachine.h"
#include "ui/MenuTree.h"
#include "version_gen.h" // generated by scripts/git_version.py

namespace {
const ulong RENDER_PERIOD_MS = 200; // 5 redraws per second at most
const ulong RADAR_ALIVE_MS = 3000;
const ulong ANIMATION_HOLD_MS = 800; // the animation stays this long after the wings stop
portMUX_TYPE screenLock = portMUX_INITIALIZER_UNLOCKED; // `shown` is read by the web server task

const char *YesNo(bool value, bool french) { return value ? (french ? "oui" : "yes") : (french ? "non" : "no"); }

const char *AxisName(uint8_t axis) {
  static const char *names[] = {"-", "+X", "-X", "+Y", "-Y", "+Z", "-Z"};
  return names[axis <= 6 ? axis : 0];
}

const char *PositionName(WingPosition position, bool french) {
  switch (position) {
  case WingPosition::Open: return french ? "ouvert" : "open";
  case WingPosition::Closed: return french ? "fermé" : "closed";
  default: return french ? "entre" : "between";
  }
}

// "[#######        ]" for a 12-bit ADC value.
void Bar(uint16_t value, char *text, size_t size) {
  const int width = 15;
  int filled = (int)value * width / 4095;
  char bar[width + 1];
  for (int i = 0; i < width; i++) {
    bar[i] = i < filled ? '#' : ' ';
  }
  bar[width] = '\0';
  snprintf(text, size, "[%s]", bar);
}

void AppendJson(String &out, const char *text) {
  out += '"';
  for (const char *c = text; *c; c++) {
    if (*c == '"' || *c == '\\') {
      out += '\\';
    }
    if ((uint8_t)*c >= 0x20) {
      out += *c;
    }
  }
  out += '"';
}
} // namespace

void DebugUi::Initialize(Turret &turretIn, StateMachine &stateMachineIn, Actions &actionsIn,
                         AccessPoint &accessPointIn, Station &stationIn) {
  turret = &turretIn;
  stateMachine = &stateMachineIn;
  actions = &actionsIn;
  accessPoint = &accessPointIn;
  station = &stationIn;

  logic::MenuHooks hooks = {this, ExecuteHook, ValueHook, InfoHook};
  nav = new logic::MenuNav(ui::MENU_TREE, ui::MENU_TREE_COUNT, hooks);

  display.Begin(turret->settings.GetInt(SettingId::OledType));
  if (IsMenuActive()) {
    Log.println(display.IsPresent() ? "Debug mode: menu on the OLED, A / B navigate"
                                    : "Debug mode: no OLED, menu on the web page and with \"key\"");
  }
}

bool DebugUi::IsMenuActive() const { return turret != nullptr && turret->board.IsBenchMode(); }

logic::Lang DebugUi::Language() const {
  return turret->settings.GetInt(SettingId::Language) == 0 ? logic::Lang::English : logic::Lang::French;
}

void DebugUi::Key(logic::MenuKey key) {
  if (nav == nullptr || !IsMenuActive()) {
    return;
  }
  nav->Key(key, millis());
  dirty = true;
}

void DebugUi::Update(ulong now) {
  if (nav == nullptr) {
    return;
  }
  if (!dirty && now - lastRender < RENDER_PERIOD_MS) {
    return;
  }
  lastRender = now;
  dirty = false;

  // Wing animation (OledAnim): while a wing moves, and a little after, the
  // screen shows the turret opening or closing, in both modes.
  Wing &left = turret->gantry.GetWingLeft();
  Wing &right = turret->gantry.GetWingRight();
  bool moving = left.IsMoving() || right.IsMoving();
  if (moving) {
    animationUntil = now + ANIMATION_HOLD_MS;
    animating = true;
  } else if (animating && (long)(now - animationUntil) >= 0) {
    animating = false;
  }

  logic::MenuScreen screen;
  if (animating && turret->settings.GetBool(SettingId::OledAnim)) {
    logic::RenderWings(screen, Language(), left.GetOpenPercent(), right.GetOpenPercent(), moving);
  } else if (IsMenuActive()) {
    nav->Render(screen, Language(), now);
  } else {
    RenderStatus(screen, Language() == logic::Lang::French);
  }
  // A frame takes about 25 ms on the bus: only when something changed.
  if (memcmp(&screen, &shown, sizeof(screen)) != 0) {
    portENTER_CRITICAL(&screenLock);
    shown = screen;
    portEXIT_CRITICAL(&screenLock);
    display.Show(screen);
  }
}

// Normal mode with a screen plugged in (M6): one page, no navigation.
void DebugUi::RenderStatus(logic::MenuScreen &screen, bool french) {
  memset(&screen, 0, sizeof(screen));
  screen.highlight = -1;
  snprintf(screen.line[0], logic::SCREEN_LINE_BYTES, "Portal Turret");
  InfoLine(ui::PageState, 0, french, screen.line[1], logic::SCREEN_LINE_BYTES);
  InfoLine(ui::PageState, 1, french, screen.line[2], logic::SCREEN_LINE_BYTES);
  InfoLine(ui::PageNetwork, 2, french, screen.line[3], logic::SCREEN_LINE_BYTES);
  InfoLine(ui::PageNetwork, 3, french, screen.line[4], logic::SCREEN_LINE_BYTES);
  snprintf(screen.line[5], logic::SCREEN_LINE_BYTES, "%s", FIRMWARE_VERSION);
}

// ------------------------------------------------------------------ hooks

void DebugUi::ExecuteHook(void *context, const char *command, char *answer, size_t size) {
  DebugUi *self = static_cast<DebugUi *>(context);
  Log.printf("menu> %s\n", command);
  String result = self->actions->Execute(String(command));
  Log.println(result);
  strlcpy(answer, result.c_str(), size);
}

int32_t DebugUi::ValueHook(void *context, const char *key) {
  DebugUi *self = static_cast<DebugUi *>(context);
  if (key == nullptr || key[0] == '@') {
    return 90; // servo entries start at the middle
  }
  SettingId id;
  return self->turret->settings.FindId(key, id) ? self->turret->settings.GetInt(id) : 0;
}

void DebugUi::InfoHook(void *context, int16_t page, uint8_t line, logic::Lang lang, char *text, size_t size) {
  static_cast<DebugUi *>(context)->InfoLine(page, line, lang == logic::Lang::French, text, size);
}

// ------------------------------------------------------------------ information pages

void DebugUi::InfoLine(int16_t page, uint8_t line, bool french, char *text, size_t size) {
  Board &board = turret->board;
  Gantry &gantry = turret->gantry;
  Settings &settings = turret->settings;
  text[0] = '\0';

  switch (page) {
  case ui::PageState:
    if (line == 0) {
      snprintf(text, size, "%s: %s", french ? "État" : "State",
               StateMachine::StateName(stateMachine->GetCurrentStateId()));
    } else if (line == 1) {
      // Same numbers as the red LED blink codes.
      int length = snprintf(text, size, "%s:", french ? "Défauts" : "Faults");
      bool any = false;
      for (uint8_t n = 1; n <= 6 && length < (int)size; n++) {
        if (board.GetFaults() & (1u << (n - 1))) {
          length += snprintf(text + length, size - length, " %u", n);
          any = true;
        }
      }
      if (!any && length < (int)size) {
        snprintf(text + length, size - length, " %s", french ? "aucun" : "none");
      }
    } else if (line == 2) {
      ulong seconds = millis() / 1000;
      snprintf(text, size, "%s: %lu h %02lu min %02lu", french ? "Durée" : "Up", seconds / 3600,
               (seconds / 60) % 60, seconds % 60);
    } else {
      snprintf(text, size, "%s", FIRMWARE_VERSION);
    }
    break;

  case ui::PagePower:
    if (line == 0) {
      snprintf(text, size, "PWR_FLT: %s", board.IsPowerFault() ? (french ? "BAS (défaut)" : "LOW (fault)") : "ok");
    } else if (line == 1) {
      snprintf(text, size, "eFuse:%u brownout:%u", (unsigned)board.GetPowerFaultCount(),
               (unsigned)board.GetBrownoutCount());
    } else if (line == 2) {
      snprintf(text, size, "%s:%u %s", french ? "Boucles" : "Loops", (unsigned)board.GetBootLoopCount(),
               board.IsServoLimited() ? (french ? "alim PC" : "PC supply") : (french ? "alim 3 A" : "3 A supply"));
    } else {
      // First word of the reason: POWERON, PANIC, TASK_WDT...
      char reason[20];
      strlcpy(reason, Board::ResetReasonName(board.GetResetReason()), sizeof(reason));
      char *space = strchr(reason, ' ');
      if (space != nullptr) {
        *space = '\0';
      }
      snprintf(text, size, "Reset: %s", reason);
    }
    break;

  case ui::PageRadar:
    if (line == 0) {
      bool alive = turret->radar.IsAlive(RADAR_ALIVE_MS);
      snprintf(text, size, "Radar: %s, %u", alive ? (french ? "vivant" : "alive") : (french ? "muet" : "silent"),
               turret->radar.GetTargetCount());
    } else {
      const RadarTarget &target = turret->radar.GetTarget(line - 1);
      if (target.available) {
        bool inZone = turret->radar.IsInZone(target, settings.GetInt(SettingId::DetectMaxMm),
                                             settings.GetInt(SettingId::DetectAngle));
        snprintf(text, size, "%u: x%d y%d %s", line, target.x, target.y, inZone ? "ZONE" : "");
      } else {
        snprintf(text, size, "%u: -", line);
      }
    }
    break;

  case ui::PageImu: {
    Motion &motion = turret->motion;
    if (!motion.IsAvailable()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "IMU absente" : "IMU missing");
      }
      break;
    }
    const sensors_vec_t &g = motion.GetAcceleration();
    if (line == 0) {
      snprintf(text, size, "x%.1f y%.1f z%.1f", g.x, g.y, g.z);
    } else if (line == 1) {
      snprintf(text, size, "%s: %s  %s: %s", french ? "Axe" : "Axis", AxisName(motion.DominantAxis()),
               french ? "régl" : "set", AxisName(settings.GetInt(SettingId::ImuUpAxis)));
    } else if (line == 2) {
      snprintf(text, size, "%s: %s", french ? "Debout" : "Upright", YesNo(motion.IsUpright(), french));
    } else {
      snprintf(text, size, "Temp: %.1f C", motion.GetTemperature());
    }
    break;
  }

  case ui::PageHall: {
    Wing &wing = line < 2 ? gantry.GetWingLeft() : gantry.GetWingRight();
    if (line % 2 == 0) {
      snprintf(text, size, "%s: %u %s", line == 0 ? (french ? "G" : "L") : (french ? "D" : "R"),
               wing.GetLastHall(), PositionName(wing.ReadPosition(), french));
    } else {
      Bar(wing.GetLastHall(), text, size);
    }
    break;
  }

  case ui::PageServos:
    if (line < 3) {
      // Two outputs per line, in Gantry channel order; "----" = released.
      static const char *names[] = {"rotz", "rotx", "gunl", "gunr", "wngl", "wngr"};
      char part[2][12];
      for (uint8_t i = 0; i < 2; i++) {
        ServoChannel &channel = gantry.GetChannel(line * 2 + i);
        if (channel.IsAttached()) {
          snprintf(part[i], sizeof(part[i]), "%s:%d", names[line * 2 + i], channel.GetMicroseconds());
        } else {
          snprintf(part[i], sizeof(part[i]), "%s:----", names[line * 2 + i]);
        }
      }
      snprintf(text, size, "%s %s", part[0], part[1]);
    } else {
      snprintf(text, size, "%s", board.IsServoLimited() ? (french ? "Alim PC: 1 servo" : "PC supply: 1 servo")
                                                        : (french ? "Alim 3 A: tous" : "3 A supply: all"));
    }
    break;

  case ui::PageAudio: {
    Audio &audio = turret->audio;
    if (line == 0) {
      snprintf(text, size, "Gain: %ld dB", (long)audio.amp.GetGain());
    } else if (line == 1) {
      snprintf(text, size, "Volume: %ld %%", (long)settings.GetInt(SettingId::Volume));
    } else if (line == 2) {
      snprintf(text, size, "%s: %s", french ? "Muet" : "Muted", YesNo(audio.amp.IsMuted(), french));
    } else {
      snprintf(text, size, "%s: %s", french ? "Lecture" : "Playing", YesNo(audio.IsPlaying(), french));
    }
    break;
  }

  case ui::PageWifiAp:
    if (!accessPoint->IsOn()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "WiFi arrêté" : "WiFi off");
      }
    } else if (line == 0) {
      snprintf(text, size, "%s", accessPoint->GetSsid());
    } else if (line == 1) {
      snprintf(text, size, "%s", french ? "Mot de passe :" : "Password:");
    } else if (line == 2) {
      // Shown on purpose: this screen is for whoever stands at the turret
      // with the debug switch closed, to connect a phone.
      snprintf(text, size, "%s", accessPoint->GetPassword());
    } else {
      snprintf(text, size, "192.168.4.1  %u cli.", accessPoint->GetClientCount());
    }
    break;

  case ui::PageWifiHome:
    if (!station->IsEnabled()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Non réglé" : "Not set");
      } else if (line == 1) {
        snprintf(text, size, "%s", french ? "(par la page web)" : "(from the web page)");
      }
    } else if (line == 0) {
      snprintf(text, size, "%s", station->GetSsid());
    } else if (line == 1) {
      snprintf(text, size, "%s", station->IsConnected() ? (french ? "Connecté" : "Connected")
                                                        : (french ? "Connexion..." : "Connecting..."));
    } else if (station->IsConnected()) {
      if (line == 2) {
        snprintf(text, size, "%s %d", station->GetIp(), station->GetRssi()); // address, signal in dBm
      } else {
        snprintf(text, size, "%s.local", Station::HOSTNAME);
      }
    }
    break;

  case ui::PageWifiScan:
    if (station->IsScanning()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Scan en cours..." : "Scanning...");
      }
    } else if (station->GetFoundCount() == 0) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Aucun (Scanner)" : "None (Scan networks)");
      }
    } else if (line < station->GetFoundCount()) {
      // 16 characters of the name, then the signal in dBm.
      snprintf(text, size, "%.16s %d", station->GetFoundSsid(line), station->GetFoundRssi(line));
    }
    break;

  case ui::PageTime: {
    String time = Station::LocalTime(); // "YYYY-MM-DD HH:MM:SS", empty before NTP
    if (line == 0) {
      snprintf(text, size, "%s", time.length() ? time.substring(0, 10).c_str() : (french ? "Heure non réglée" : "Time not set"));
    } else if (line == 1) {
      snprintf(text, size, "%s", time.length() ? time.substring(11).c_str() : (french ? "(réseau maison)" : "(home network)"));
    } else if (line == 2) {
      snprintf(text, size, "NTP: %s", YesNo(Station::HasTime(), french));
    } else {
      snprintf(text, size, "%.21s", settings.GetString(SettingId::Timezone));
    }
    break;
  }

  case ui::PageNetwork:
    if (line == 0) {
      snprintf(text, size, "AP: %s", accessPoint->IsOn() ? accessPoint->GetSsid() : (french ? "arrêté" : "off"));
    } else if (line == 1) {
      snprintf(text, size, "Clients: %u", accessPoint->GetClientCount());
    } else if (line == 2) {
      if (!station->IsEnabled()) {
        snprintf(text, size, "%s", french ? "Maison: non réglé" : "Home: not set");
      } else if (station->IsConnected()) {
        snprintf(text, size, "%s %d", station->GetIp(), station->GetRssi());
      } else {
        snprintf(text, size, "%s", french ? "Maison: connexion" : "Home: connecting");
      }
    } else {
      // "YYYY-MM-DD HH:MM:SS" -> keep "MM-DD HH:MM:SS"
      String time = Station::LocalTime();
      snprintf(text, size, "%s", time.length() > 5 ? time.c_str() + 5 : (french ? "Heure: --" : "Time: --"));
    }
    break;
  }
}

// ------------------------------------------------------------------ outputs

String DebugUi::ScreenJson() {
  logic::MenuScreen copy;
  portENTER_CRITICAL(&screenLock);
  copy = shown;
  portEXIT_CRITICAL(&screenLock);

  String json = String("{\"present\":") + (display.IsPresent() ? "true" : "false") +
                ",\"menu\":" + (IsMenuActive() ? "true" : "false") +
                ",\"highlight\":" + String(copy.highlight) + ",\"lines\":[";
  for (uint8_t i = 0; i < logic::SCREEN_LINES; i++) {
    json += i ? "," : "";
    AppendJson(json, copy.line[i]);
  }
  json += "]}";
  return json;
}

String DebugUi::ScreenText() {
  String text;
  for (uint8_t i = 0; i < logic::SCREEN_LINES; i++) {
    text += (i == shown.highlight) ? "> " : "  ";
    text += shown.line[i];
    text += "\n";
  }
  return text;
}
