#include "DebugUi.h"

#include "board/CoreDump.h"
#include "board/Log.h"
#include "control/Actions.h"
#include "control/SelfTest.h"
#include "states/StateMachine.h"
#include "ui/MenuTree.h"
#include "version_gen.h" // generated by scripts/git_version.py
#include <qrcode.h>      // QR code generator of the ESP32 SDK (esp_qrcode_generate)

namespace {
const ulong RENDER_PERIOD_MS = 200;    // 5 redraws per second at most
const ulong ANIMATION_PERIOD_MS = 100; // 10 per second while the wings move
const ulong RADAR_ALIVE_MS = 3000;
const ulong ANIMATION_HOLD_MS = 800; // the animation stays this long after the wings stop
const ulong HALL_SAMPLE_MS = 50;
const ulong SUBTITLE_MS = 4000;
portMUX_TYPE screenLock = portMUX_INITIALIZER_UNLOCKED; // `shown` is read by the web server task

const char *YesNo(bool value, bool french) { return value ? (french ? "oui" : "yes") : (french ? "non" : "no"); }

const char *AxisName(uint8_t axis) {
  static const char *names[] = {"-", "+X", "-X", "+Y", "-Y", "+Z", "-Z"};
  return names[axis <= 6 ? axis : 0];
}

const char *PositionName(WingPosition position, bool french) {
  switch (position) {
  case WingPosition::Open: return french ? "ouvert" : "open";
  case WingPosition::Closed: return french ? "fermé" : "closed";
  default: return french ? "entre" : "between";
  }
}

// "[#######        ]" for a 12-bit ADC value.
void Bar(uint16_t value, char *text, size_t size) {
  const int width = 15;
  int filled = (int)value * width / 4095;
  char bar[width + 1];
  for (int i = 0; i < width; i++) {
    bar[i] = i < filled ? '#' : ' ';
  }
  bar[width] = '\0';
  snprintf(text, size, "[%s]", bar);
}

void AppendJson(String &out, const char *text) {
  out += '"';
  for (const char *c = text; *c; c++) {
    if (*c == '"' || *c == '\\') {
      out += '\\';
    }
    if ((uint8_t)*c >= 0x20) {
      out += *c;
    }
  }
  out += '"';
}

// The n-th line from the end of a text (0 = last), without its line break.
String LineFromEnd(const String &text, int fromEnd) {
  int end = text.length();
  while (end > 0 && (text[end - 1] == '\n' || text[end - 1] == '\r')) {
    end--;
  }
  for (;;) {
    int start = text.lastIndexOf('\n', end - 1);
    if (fromEnd == 0) {
      return text.substring(start + 1, end);
    }
    if (start < 0) {
      return String();
    }
    end = start;
    fromEnd--;
  }
}

// QR code produced by the SDK generator, kept as a bitmap (row by row, MSB first).
uint8_t qrModules[logic::SCREEN_DATA_BYTES];
int qrSize = 0;

void QrCallback(esp_qrcode_handle_t qrcode) {
  int size = esp_qrcode_get_size(qrcode);
  memset(qrModules, 0, sizeof(qrModules));
  qrSize = 0;
  if (size <= 0 || size * size > (int)sizeof(qrModules) * 8) {
    return; // too big for the screen anyway
  }
  for (int y = 0; y < size; y++) {
    for (int x = 0; x < size; x++) {
      if (esp_qrcode_get_module(qrcode, x, y)) {
        int bit = y * size + x;
        qrModules[bit / 8] |= 0x80 >> (bit % 8);
      }
    }
  }
  qrSize = size;
}

// Field of a "WIFI:" QR code: \ ; , : " are escaped with a backslash.
void AppendWifiField(String &out, const char *text) {
  for (const char *c = text; *c; c++) {
    if (*c == '\\' || *c == ';' || *c == ',' || *c == ':' || *c == '"') {
      out += '\\';
    }
    out += *c;
  }
}
} // namespace

void DebugUi::Initialize(Turret &turretIn, StateMachine &stateMachineIn, Actions &actionsIn,
                         AccessPoint &accessPointIn, Station &stationIn, SelfTest &selfTestIn) {
  turret = &turretIn;
  stateMachine = &stateMachineIn;
  actions = &actionsIn;
  accessPoint = &accessPointIn;
  station = &stationIn;
  selfTest = &selfTestIn;

  logic::MenuHooks hooks = {this, ExecuteHook, ValueHook, InfoHook, GraphicHook};
  nav = new logic::MenuNav(ui::MENU_TREE, ui::MENU_TREE_COUNT, hooks);

  display.Begin(turret->settings.GetInt(SettingId::OledType));
  ApplySettings();
  lastActivity = millis();
  if (IsMenuActive()) {
    Log.println(display.IsPresent() ? "Debug mode: menu on the OLED, A / B navigate"
                                    : "Debug mode: no OLED, menu on the web page and with \"key\"");
  }
}

void DebugUi::ApplySettings() {
  if (turret == nullptr) {
    return;
  }
  display.Configure(turret->settings.GetBool(SettingId::OledFlip),
                    (uint8_t)turret->settings.GetInt(SettingId::OledContrast));
  dirty = true;
}

bool DebugUi::IsMenuActive() const { return turret != nullptr && turret->board.IsBenchMode(); }

logic::Lang DebugUi::Language() const {
  return turret->settings.GetInt(SettingId::Language) == 0 ? logic::Lang::English : logic::Lang::French;
}

void DebugUi::Wake(ulong now) {
  lastActivity = now;
  if (asleep) {
    asleep = false;
    display.SetPower(true);
    dirty = true;
  }
}

void DebugUi::Key(logic::MenuKey key) {
  if (nav == nullptr) {
    return;
  }
  // A key press on a sleeping screen only wakes it up.
  bool wasAsleep = asleep;
  Wake(millis());
  if (wasAsleep || !IsMenuActive()) {
    return;
  }
  nav->Key(key, millis());
  dirty = true;
}

// OLEDs burn in: off after OledSleepS without a key, a movement, a state
// change or a power fault. Anything of those wakes it.
void DebugUi::UpdateSleep(ulong now, bool moving) {
  StateId state = stateMachine->GetCurrentStateId();
  if (moving || state != lastState || turret->board.IsPowerFault()) {
    Wake(now);
  }
  ulong delayMs = (ulong)turret->settings.GetInt(SettingId::OledSleepS) * 1000;
  if (!asleep && delayMs > 0 && now - lastActivity >= delayMs) {
    asleep = true;
    display.SetPower(false);
  }
}

void DebugUi::SampleHall(ulong now) {
  if (now - lastSample < HALL_SAMPLE_MS) {
    return;
  }
  lastSample = now;
  hallSamples[0][hallHead] = turret->gantry.GetWingLeft().GetLastHall() >> 4;
  hallSamples[1][hallHead] = turret->gantry.GetWingRight().GetLastHall() >> 4;
  hallHead = (hallHead + 1) % GRAPH_SAMPLES;
}

void DebugUi::Update(ulong now) {
  if (nav == nullptr) {
    return;
  }
  SampleHall(now);

  // Wing animation (OledAnim): while a wing moves, and a little after, the
  // screen shows the turret opening or closing, in both modes.
  Wing &left = turret->gantry.GetWingLeft();
  Wing &right = turret->gantry.GetWingRight();
  bool moving = left.IsMoving() || right.IsMoving();
  if (moving) {
    animationUntil = now + ANIMATION_HOLD_MS;
    animating = true;
  } else if (animating && (long)(now - animationUntil) >= 0) {
    animating = false;
  }
  UpdateSleep(now, moving);

  // Subtitle of the eye at each change of state.
  StateId state = stateMachine->GetCurrentStateId();
  if (state != lastState) {
    bool french = Language() == logic::Lang::French;
    switch (state) {
    case StateId::Booting: subtitle = french ? "Mode sentinelle activé" : "Sentry mode activated"; break;
    case StateId::Activate: subtitle = french ? "Cible acquise" : "Target acquired"; break;
    case StateId::FiringState: subtitle = french ? "Te voilà." : "There you are."; break;
    case StateId::Disengage: subtitle = french ? "Cible perdue" : "Target lost"; break;
    case StateId::Idle: subtitle = lastState == StateId::Disengage ? (french ? "Toujours là ?" : "Are you still there?") : ""; break;
    case StateId::Fault: subtitle = french ? "Erreur critique" : "Critical error"; break;
    case StateId::Manual: subtitle = french ? "Arrêt" : "Shutting down"; break;
    }
    subtitleUntil = now + SUBTITLE_MS;
    lastState = state;
    dirty = true;
  }

  // Twice as often during the wing animation: the frames are sent by the
  // display task, so this costs loop() nothing but the copy of the screen.
  if (!dirty && now - lastRender < (animating ? ANIMATION_PERIOD_MS : RENDER_PERIOD_MS)) {
    return;
  }
  lastRender = now;
  dirty = false;

  // Static: ~480 bytes that do not need to live on the loop stack.
  static logic::MenuScreen screen;
  bool french = Language() == logic::Lang::French;
  if (animating && turret->settings.GetBool(SettingId::OledAnim)) {
    logic::RenderWings(screen, Language(), left.GetOpenPercent(), right.GetOpenPercent(), moving);
  } else if (IsMenuActive()) {
    nav->Render(screen, Language(), now);
  } else if (turret->settings.GetBool(SettingId::OledFace)) {
    RenderFace(screen, french, now);
  } else {
    RenderStatus(screen, french);
  }
  // A frame keeps the I2C bus busy about 25 ms (in the display task, not
  // here): only when something changed.
  if (memcmp(&screen, &shown, sizeof(screen)) != 0) {
    portENTER_CRITICAL(&screenLock);
    shown = screen;
    portEXIT_CRITICAL(&screenLock);
    display.Show(screen);
  }
}

// Normal mode with a screen plugged in (M6), OledFace off: one page, no navigation.
void DebugUi::RenderStatus(logic::MenuScreen &screen, bool french) {
  memset(&screen, 0, sizeof(screen));
  screen.highlight = -1;
  snprintf(screen.line[0], logic::SCREEN_LINE_BYTES, "Portal Turret");
  InfoLine(ui::PageState, 0, french, screen.line[1], logic::SCREEN_LINE_BYTES);
  InfoLine(ui::PageState, 1, french, screen.line[2], logic::SCREEN_LINE_BYTES);
  InfoLine(ui::PageNetwork, 2, french, screen.line[3], logic::SCREEN_LINE_BYTES);
  InfoLine(ui::PageNetwork, 3, french, screen.line[4], logic::SCREEN_LINE_BYTES);
  snprintf(screen.line[5], logic::SCREEN_LINE_BYTES, "%s", FIRMWARE_VERSION);
}

// Normal mode, OledFace on: the eye of the turret. Asleep while idle with
// nobody in sight, awake and looking at the first target otherwise, angry
// while it deploys and fires. Active faults replace the first subtitle line.
void DebugUi::RenderFace(logic::MenuScreen &screen, bool french, ulong now) {
  memset(&screen, 0, sizeof(screen));
  screen.highlight = -1;
  screen.graphic = logic::Graphic::Eye;

  StateId state = stateMachine->GetCurrentStateId();
  int16_t gaze = 0;
  bool target = false;
  if (turret->radar.IsAlive(RADAR_ALIVE_MS)) {
    for (uint8_t i = 0; i < TRACK_COUNT && !target; i++) {
      const RadarTarget &t = turret->radar.GetTarget(i);
      if (t.available && t.y > 0) {
        // Angle of the target seen from the radar: 60 degrees = full deflection.
        float angle = atan2f((float)t.x, (float)t.y) * 180.0f / PI;
        gaze = (int16_t)constrain((int)(angle * 100 / 60), -100, 100);
        target = true;
      }
    }
  }
  int16_t mood = 1;
  if (state == StateId::Activate || state == StateId::FiringState) {
    mood = 2;
  } else if (state == StateId::Fault || ((state == StateId::Idle || state == StateId::Manual) && !target)) {
    mood = 0;
  }
  screen.value[0] = gaze;
  screen.value[1] = mood;
  snprintf(screen.line[0], logic::SCREEN_LINE_BYTES, "%s", mood == 0 ? "(-)" : mood == 2 ? "(O)!" : "(o)");

  if (turret->board.GetFaults() != 0) {
    InfoLine(ui::PageState, 1, french, screen.line[4], logic::SCREEN_LINE_BYTES);
  }
  if (subtitle[0] != '\0' && (long)(subtitleUntil - now) > 0) {
    snprintf(screen.line[5], logic::SCREEN_LINE_BYTES, "%s", subtitle);
  } else {
    // Nothing to say: the time (hours and minutes) once NTP has set it.
    String time = Station::LocalTime();
    if (time.length() >= 16) {
      snprintf(screen.line[5], logic::SCREEN_LINE_BYTES, "%s", time.substring(11, 16).c_str());
    }
  }
}

// ------------------------------------------------------------------ hooks

void DebugUi::ExecuteHook(void *context, const char *command, char *answer, size_t size) {
  DebugUi *self = static_cast<DebugUi *>(context);
  Log.printf("menu> %s\n", command);
  String result = self->actions->Execute(String(command));
  Log.println(result);
  strlcpy(answer, result.c_str(), size);
}

int32_t DebugUi::ValueHook(void *context, const char *key) {
  DebugUi *self = static_cast<DebugUi *>(context);
  if (key == nullptr || key[0] == '@') {
    return 90; // servo entries start at the middle
  }
  SettingId id;
  return self->turret->settings.FindId(key, id) ? self->turret->settings.GetInt(id) : 0;
}

void DebugUi::InfoHook(void *context, int16_t page, uint8_t line, logic::Lang lang, char *text, size_t size) {
  static_cast<DebugUi *>(context)->InfoLine(page, line, lang == logic::Lang::French, text, size);
}

void DebugUi::GraphicHook(void *context, int16_t page, logic::MenuScreen &screen) {
  static_cast<DebugUi *>(context)->InfoGraphic(page, screen);
}

// ------------------------------------------------------------------ pages with a drawing

void DebugUi::FillQr(logic::MenuScreen &screen, const char *text) {
  if (strcmp(text, qrText) != 0) {
    strlcpy(qrText, text, sizeof(qrText));
    // Version 3 (29 modules) is drawn at 2 pixels per module; up to version 6
    // (41 modules) still fits at 1 pixel per module.
    esp_qrcode_config_t config = {QrCallback, 6, ESP_QRCODE_ECC_LOW};
    if (esp_qrcode_generate(&config, text) != ESP_OK) {
      qrSize = 0;
    }
  }
  screen.graphic = logic::Graphic::Qr;
  screen.value[0] = (int16_t)qrSize;
  screen.dataLength = (uint8_t)((qrSize * qrSize + 7) / 8);
  memcpy(screen.data, qrModules, sizeof(screen.data));
}

void DebugUi::InfoGraphic(int16_t page, logic::MenuScreen &screen) {
  Settings &settings = turret->settings;
  bool french = Language() == logic::Lang::French;

  switch (page) {
  case ui::PageRadarView:
    screen.graphic = logic::Graphic::Radar;
    for (uint8_t i = 0; i < 3; i++) {
      const RadarTarget &target = turret->radar.GetTarget(i);
      bool visible = target.available && turret->radar.IsAlive(RADAR_ALIVE_MS);
      screen.value[i * 2] = visible ? target.x : 0;
      screen.value[i * 2 + 1] = visible ? target.y : 0;
    }
    screen.value[6] = (int16_t)settings.GetInt(SettingId::DetectMaxMm);
    screen.value[7] = (int16_t)settings.GetInt(SettingId::DetectAngle);
    break;

  case ui::PageHallGraphLeft:
  case ui::PageHallGraphRight: {
    uint8_t side = page == ui::PageHallGraphLeft ? 0 : 1;
    Wing &wing = side == 0 ? turret->gantry.GetWingLeft() : turret->gantry.GetWingRight();
    screen.graphic = logic::Graphic::Graph;
    // Oldest sample first: the curve scrolls to the left.
    for (uint8_t i = 0; i < GRAPH_SAMPLES; i++) {
      screen.data[i] = hallSamples[side][(hallHead + i) % GRAPH_SAMPLES];
    }
    screen.dataLength = GRAPH_SAMPLES;
    screen.value[0] = (int16_t)(settings.GetInt(side == 0 ? SettingId::HallOpenL : SettingId::HallOpenR) >> 4);
    screen.value[1] = (int16_t)(settings.GetInt(side == 0 ? SettingId::HallCloseL : SettingId::HallCloseR) >> 4);
    snprintf(screen.line[0], logic::SCREEN_LINE_BYTES, "Hall %s %u", side == 0 ? (french ? "G" : "L") : (french ? "D" : "R"),
             wing.GetLastHall());
    break;
  }

  case ui::PageQrWifi: {
    // Standard "join this WiFi" code: the phone camera offers to connect.
    String text = "WIFI:T:WPA;S:";
    AppendWifiField(text, accessPoint->GetSsid());
    text += ";P:";
    AppendWifiField(text, accessPoint->GetPassword());
    text += ";;";
    FillQr(screen, text.c_str());
    snprintf(screen.line[0], logic::SCREEN_LINE_BYTES, "WiFi");
    snprintf(screen.line[1], logic::SCREEN_LINE_BYTES, "%.10s", accessPoint->GetSsid());
    snprintf(screen.line[2], logic::SCREEN_LINE_BYTES, "%.10s", strlen(accessPoint->GetSsid()) > 10 ? accessPoint->GetSsid() + 10 : "");
    snprintf(screen.line[3], logic::SCREEN_LINE_BYTES, "%s", qrSize ? "" : (french ? "trop long" : "too long"));
    snprintf(screen.line[4], logic::SCREEN_LINE_BYTES, "A:page");
    snprintf(screen.line[5], logic::SCREEN_LINE_BYTES, "%s", french ? "B:retour" : "B:back");
    break;
  }

  case ui::PageQrWeb: {
    // On the home network if connected, on the turret network otherwise.
    String url = String("http://") + (station->IsConnected() ? station->GetIp() : "192.168.4.1");
    FillQr(screen, url.c_str());
    snprintf(screen.line[0], logic::SCREEN_LINE_BYTES, "Web");
    snprintf(screen.line[1], logic::SCREEN_LINE_BYTES, "%.10s", url.c_str() + 7);
    snprintf(screen.line[2], logic::SCREEN_LINE_BYTES, "%.10s", url.length() > 17 ? url.c_str() + 17 : "");
    snprintf(screen.line[3], logic::SCREEN_LINE_BYTES, "turret");
    snprintf(screen.line[4], logic::SCREEN_LINE_BYTES, "A:page");
    snprintf(screen.line[5], logic::SCREEN_LINE_BYTES, "%s", french ? "B:retour" : "B:back");
    break;
  }
  }
}

// ------------------------------------------------------------------ information pages

void DebugUi::InfoLine(int16_t page, uint8_t line, bool french, char *text, size_t size) {
  Board &board = turret->board;
  Gantry &gantry = turret->gantry;
  Settings &settings = turret->settings;
  text[0] = '\0';

  switch (page) {
  case ui::PageState:
    if (line == 0) {
      snprintf(text, size, "%s: %s", french ? "État" : "State",
               StateMachine::StateName(stateMachine->GetCurrentStateId()));
    } else if (line == 1) {
      // Same numbers as the red LED blink codes.
      int length = snprintf(text, size, "%s:", french ? "Défauts" : "Faults");
      bool any = false;
      for (uint8_t n = 1; n <= 6 && length < (int)size; n++) {
        if (board.GetFaults() & (1u << (n - 1))) {
          length += snprintf(text + length, size - length, " %u", n);
          any = true;
        }
      }
      if (!any && length < (int)size) {
        snprintf(text + length, size - length, " %s", french ? "aucun" : "none");
      }
    } else if (line == 2) {
      ulong seconds = millis() / 1000;
      snprintf(text, size, "%s: %lu h %02lu min %02lu", french ? "Durée" : "Up", seconds / 3600,
               (seconds / 60) % 60, seconds % 60);
    } else {
      snprintf(text, size, "%s", FIRMWARE_VERSION);
    }
    break;

  case ui::PagePower:
    if (line == 0) {
      snprintf(text, size, "PWR_FLT: %s", board.IsPowerFault() ? (french ? "BAS (défaut)" : "LOW (fault)") : "ok");
    } else if (line == 1) {
      snprintf(text, size, "eFuse:%u brownout:%u", (unsigned)board.GetPowerFaultCount(),
               (unsigned)board.GetBrownoutCount());
    } else if (line == 2) {
      snprintf(text, size, "%s:%u %s", french ? "Boucles" : "Loops", (unsigned)board.GetBootLoopCount(),
               board.IsServoLimited() ? (french ? "alim PC" : "PC supply") : (french ? "alim 3 A" : "3 A supply"));
    } else {
      // First word of the reason: POWERON, PANIC, TASK_WDT...
      char reason[20];
      strlcpy(reason, Board::ResetReasonName(board.GetResetReason()), sizeof(reason));
      char *space = strchr(reason, ' ');
      if (space != nullptr) {
        *space = '\0';
      }
      snprintf(text, size, "Reset: %s", reason);
    }
    break;

  case ui::PageRadar:
  case ui::PageRadarView: // text version of the radar view
    if (line == 0) {
      bool alive = turret->radar.IsAlive(RADAR_ALIVE_MS);
      snprintf(text, size, "Radar: %s, %u", alive ? (french ? "vivant" : "alive") : (french ? "muet" : "silent"),
               turret->radar.GetTargetCount());
    } else {
      const RadarTarget &target = turret->radar.GetTarget(line - 1);
      if (target.available) {
        bool inZone = turret->radar.IsInZone(target, settings.GetInt(SettingId::DetectMaxMm),
                                             settings.GetInt(SettingId::DetectAngle));
        snprintf(text, size, "%u: x%d y%d %s", line, target.x, target.y, inZone ? "ZONE" : "");
      } else {
        snprintf(text, size, "%u: -", line);
      }
    }
    break;

  case ui::PageImu: {
    Motion &motion = turret->motion;
    if (!motion.IsAvailable()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "IMU absente" : "IMU missing");
      }
      break;
    }
    const sensors_vec_t &g = motion.GetAcceleration();
    if (line == 0) {
      snprintf(text, size, "x%.1f y%.1f z%.1f", g.x, g.y, g.z);
    } else if (line == 1) {
      snprintf(text, size, "%s: %s  %s: %s", french ? "Axe" : "Axis", AxisName(motion.DominantAxis()),
               french ? "régl" : "set", AxisName(settings.GetInt(SettingId::ImuUpAxis)));
    } else if (line == 2) {
      snprintf(text, size, "%s: %s", french ? "Debout" : "Upright", YesNo(motion.IsUpright(), french));
    } else {
      snprintf(text, size, "Temp: %.1f C", motion.GetTemperature());
    }
    break;
  }

  case ui::PageHall: {
    Wing &wing = line < 2 ? gantry.GetWingLeft() : gantry.GetWingRight();
    if (line % 2 == 0) {
      snprintf(text, size, "%s: %u %s", line == 0 ? (french ? "G" : "L") : (french ? "D" : "R"),
               wing.GetLastHall(), PositionName(wing.ReadPosition(), french));
    } else {
      Bar(wing.GetLastHall(), text, size);
    }
    break;
  }

  case ui::PageHallGraphLeft:
  case ui::PageHallGraphRight: { // text version of the curve: value, position, thresholds
    bool leftSide = page == ui::PageHallGraphLeft;
    Wing &wing = leftSide ? gantry.GetWingLeft() : gantry.GetWingRight();
    if (line == 0) {
      snprintf(text, size, "%u %s", wing.GetLastHall(), PositionName(wing.ReadPosition(), french));
    } else if (line == 1) {
      Bar(wing.GetLastHall(), text, size);
    } else if (line == 2) {
      snprintf(text, size, "%s: %ld", french ? "ouvert" : "open",
               (long)settings.GetInt(leftSide ? SettingId::HallOpenL : SettingId::HallOpenR));
    } else {
      snprintf(text, size, "%s: %ld", french ? "fermé" : "closed",
               (long)settings.GetInt(leftSide ? SettingId::HallCloseL : SettingId::HallCloseR));
    }
    break;
  }

  case ui::PageServos:
    if (line < 3) {
      // Two outputs per line, in Gantry channel order; "----" = released.
      static const char *names[] = {"rotz", "rotx", "gunl", "gunr", "wngl", "wngr"};
      char part[2][12];
      for (uint8_t i = 0; i < 2; i++) {
        ServoChannel &channel = gantry.GetChannel(line * 2 + i);
        if (channel.IsAttached()) {
          snprintf(part[i], sizeof(part[i]), "%s:%d", names[line * 2 + i], channel.GetMicroseconds());
        } else {
          snprintf(part[i], sizeof(part[i]), "%s:----", names[line * 2 + i]);
        }
      }
      snprintf(text, size, "%s %s", part[0], part[1]);
    } else {
      snprintf(text, size, "%s", board.IsServoLimited() ? (french ? "Alim PC: 1 servo" : "PC supply: 1 servo")
                                                        : (french ? "Alim 3 A: tous" : "3 A supply: all"));
    }
    break;

  case ui::PageAudio: {
    Audio &audio = turret->audio;
    if (line == 0) {
      snprintf(text, size, "Gain: %ld dB", (long)audio.amp.GetGain());
    } else if (line == 1) {
      snprintf(text, size, "Volume: %ld %%", (long)settings.GetInt(SettingId::Volume));
    } else if (line == 2) {
      snprintf(text, size, "%s: %s", french ? "Muet" : "Muted", YesNo(audio.amp.IsMuted(), french));
    } else {
      snprintf(text, size, "%s: %s", french ? "Lecture" : "Playing", YesNo(audio.IsPlaying(), french));
    }
    break;
  }

  case ui::PageWifiAp:
    if (!accessPoint->IsOn()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "WiFi arrêté" : "WiFi off");
      }
    } else if (line == 0) {
      snprintf(text, size, "%s", accessPoint->GetSsid());
    } else if (line == 1) {
      snprintf(text, size, "%s", french ? "Mot de passe :" : "Password:");
    } else if (line == 2) {
      // Shown on purpose: this screen is for whoever stands at the turret
      // with the debug switch closed, to connect a phone.
      snprintf(text, size, "%s", accessPoint->GetPassword());
    } else {
      snprintf(text, size, "192.168.4.1  %u cli.", accessPoint->GetClientCount());
    }
    break;

  case ui::PageWifiHome:
    if (!station->IsEnabled()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Non réglé" : "Not set");
      } else if (line == 1) {
        snprintf(text, size, "%s", french ? "(par la page web)" : "(from the web page)");
      }
    } else if (line == 0) {
      snprintf(text, size, "%s", station->GetSsid());
    } else if (line == 1) {
      snprintf(text, size, "%s", station->IsConnected() ? (french ? "Connecté" : "Connected")
                                                        : (french ? "Connexion..." : "Connecting..."));
    } else if (station->IsConnected()) {
      if (line == 2) {
        snprintf(text, size, "%s %d", station->GetIp(), station->GetRssi()); // address, signal in dBm
      } else {
        snprintf(text, size, "%s.local", Station::HOSTNAME);
      }
    }
    break;

  case ui::PageWifiScan:
    if (station->IsScanning()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Scan en cours..." : "Scanning...");
      }
    } else if (station->GetFoundCount() == 0) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Aucun (Scanner)" : "None (Scan networks)");
      }
    } else if (line < station->GetFoundCount()) {
      // 16 characters of the name, then the signal in dBm.
      snprintf(text, size, "%.16s %d", station->GetFoundSsid(line), station->GetFoundRssi(line));
    }
    break;

  case ui::PageTime: {
    String time = Station::LocalTime(); // "YYYY-MM-DD HH:MM:SS", empty before NTP
    if (line == 0) {
      snprintf(text, size, "%s", time.length() ? time.substring(0, 10).c_str() : (french ? "Heure non réglée" : "Time not set"));
    } else if (line == 1) {
      snprintf(text, size, "%s", time.length() ? time.substring(11).c_str() : (french ? "(réseau maison)" : "(home network)"));
    } else if (line == 2) {
      snprintf(text, size, "NTP: %s", YesNo(Station::HasTime(), french));
    } else {
      snprintf(text, size, "%.21s", settings.GetString(SettingId::Timezone));
    }
    break;
  }

  case ui::PageNetwork:
    if (line == 0) {
      snprintf(text, size, "AP: %s", accessPoint->IsOn() ? accessPoint->GetSsid() : (french ? "arrêté" : "off"));
    } else if (line == 1) {
      snprintf(text, size, "Clients: %u", accessPoint->GetClientCount());
    } else if (line == 2) {
      if (!station->IsEnabled()) {
        snprintf(text, size, "%s", french ? "Maison: non réglé" : "Home: not set");
      } else if (station->IsConnected()) {
        snprintf(text, size, "%s %d", station->GetIp(), station->GetRssi());
      } else {
        snprintf(text, size, "%s", french ? "Maison: connexion" : "Home: connecting");
      }
    } else {
      // "YYYY-MM-DD HH:MM:SS" -> keep "MM-DD HH:MM:SS"
      String time = Station::LocalTime();
      snprintf(text, size, "%s", time.length() > 5 ? time.c_str() + 5 : (french ? "Heure: --" : "Time: --"));
    }
    break;

  case ui::PageLog: {
    // The last four lines of the log, oldest first (21 columns each on the
    // OLED). The tail is read once per page (at its first line).
    static String tail;
    if (line == 0) {
      tail = Log.Tail(400);
    }
    snprintf(text, size, "%.40s", LineFromEnd(tail, 3 - line).c_str());
    break;
  }

  case ui::PageCrash:
    if (CoreDump::Size() == 0) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Pas de coredump" : "No core dump");
      } else if (line == 1) {
        snprintf(text, size, "%s: %s", french ? "Journal précédent" : "Previous log",
                 YesNo(CrashLog::PreviousRun().length() > 0, french));
      } else {
        // Last lines logged before the reset, if any.
        snprintf(text, size, "%.40s", LineFromEnd(CrashLog::PreviousRun(), 3 - line).c_str());
      }
    } else if (line == 0) {
      snprintf(text, size, "Coredump: %u %s", (unsigned)CoreDump::Size(), french ? "o" : "B");
    } else {
      // The summary ("task x, PC 0x..., backtrace ...") over three lines.
      const String &summary = CoreDump::Summary();
      unsigned start = (line - 1) * logic::SCREEN_COLUMNS;
      if (summary.length() > start) {
        snprintf(text, size, "%.21s", summary.c_str() + start);
      }
    }
    break;

  case ui::PageStats: {
    Stats &stats = turret->stats;
    if (line == 0) {
      snprintf(text, size, "%s: %u", french ? "Démarrages" : "Boots", (unsigned)stats.GetBoots());
    } else if (line == 1) {
      snprintf(text, size, "Cycles: %u (+%u)", (unsigned)stats.GetTotalCycles(), (unsigned)stats.GetSessionCycles());
    } else if (line == 2) {
      snprintf(text, size, "%s: %u", french ? "Cibles vues" : "Targets seen", (unsigned)stats.GetSessionTargets());
    } else if (stats.GetLastCycleAt() == 0) {
      snprintf(text, size, "%s", french ? "Dernier tir: aucun" : "Last cycle: none");
    } else {
      ulong seconds = (millis() - stats.GetLastCycleAt()) / 1000;
      if (seconds < 120) {
        snprintf(text, size, "%s %lu s", french ? "Dernier tir:" : "Last cycle:", seconds);
      } else {
        snprintf(text, size, "%s %lu min", french ? "Dernier tir:" : "Last cycle:", seconds / 60);
      }
    }
    break;
  }

  case ui::PageSelfTest:
    if (!selfTest->HasRun()) {
      if (line == 0) {
        snprintf(text, size, "%s", french ? "Pas encore lancé" : "Not run yet");
      }
    } else if (line == 0) {
      snprintf(text, size, "%u OK %u %s %u %s", selfTest->Count(SelfTest::Result::Ok),
               selfTest->Count(SelfTest::Result::Fail), french ? "ECH" : "FAIL",
               selfTest->Count(SelfTest::Result::Check), french ? "voir" : "CHK");
    } else if (selfTest->IsRunning()) {
      if (line == 1) {
        snprintf(text, size, "%s", french ? "En cours :" : "Running:");
      } else if (line == 2) {
        snprintf(text, size, "%s", selfTest->CurrentName(french));
      }
    } else if (selfTest->Count(SelfTest::Result::Fail) == 0) {
      if (line == 1) {
        snprintf(text, size, "%s", french ? "Aucun échec" : "No failure");
      }
    } else {
      // The first three failed entries.
      snprintf(text, size, "%s", selfTest->NameWith(SelfTest::Result::Fail, line - 1, french));
    }
    break;
  }
}

// ------------------------------------------------------------------ outputs

String DebugUi::ScreenJson() {
  // Heap, not the stack of the web server task (the screen is ~480 bytes).
  logic::MenuScreen *copy = new logic::MenuScreen;
  portENTER_CRITICAL(&screenLock);
  *copy = shown;
  portEXIT_CRITICAL(&screenLock);

  String json = String("{\"present\":") + (display.IsPresent() ? "true" : "false") +
                ",\"menu\":" + (IsMenuActive() ? "true" : "false") +
                ",\"on\":" + (asleep ? "false" : "true") +
                ",\"graphic\":" + String((int)copy->graphic) +
                ",\"highlight\":" + String(copy->highlight) + ",\"lines\":[";
  for (uint8_t i = 0; i < logic::SCREEN_LINES; i++) {
    json += i ? "," : "";
    AppendJson(json, copy->line[i]);
  }
  json += "]}";
  delete copy;
  return json;
}

String DebugUi::ScreenText() {
  String text;
  for (uint8_t i = 0; i < logic::SCREEN_LINES; i++) {
    text += (i == shown.highlight) ? "> " : "  ";
    text += shown.line[i];
    text += "\n";
  }
  return text;
}
